apiVersion: v1
data:
  fluentd-loglevel: warn
  splunk-hostname: splunk.splunk.svc
  splunk-index: ocp
  splunk-insecure: "true"
  splunk-port: "8088"
  splunk-protocol: https
  splunk-source: openshift
  splunk-sourcetype: openshift
  td-agent.conf: |2

    <system>
      log_level "#{ENV['LOG_LEVEL'] }"
    </system>

    <source>
      @type  forward
      @id    input1
      port  24224

      <transport tls>
        cert_path /secret/fluentd/tls.crt
        private_key_path /secret/fluentd/tls.key
        private_key_passphrase "#{ENV['FLUENTD_SSL_PASSPHRASE'] }"
      </transport>



      <security>
        shared_key "#{ENV['SHARED_KEY'] }"
        self_hostname "#{ENV['HOSTNAME']}"
      </security>

    </source>

    <match **>
      @type splunk_hec
      protocol "#{ENV['SPLUNK_PROTOCOL'] }"
      insecure_ssl "#{ENV['SPLUNK_INSECURE'] }"
      hec_host "#{ENV['SPLUNK_HOST'] }"
      sourcetype "#{ENV['SPLUNK_SOURCETYPE'] }"
      source "#{ENV['SPLUNK_SOURCE'] }"
      index "#{ENV['SPLUNK_INDEX'] }"
      hec_port "#{ENV['SPLUNK_PORT'] }"
      hec_token "#{ENV['SPLUNK_TOKEN'] }"
      host "#{ENV['NODE_NAME']}"
      <buffer>
        @type memory
        chunk_limit_records 100000
        chunk_limit_size 200m
        flush_interval 5s
        flush_thread_count 1
        overflow_action block
        retry_max_times 3
        total_limit_size 600m
      </buffer>
    </match>
kind: ConfigMap
metadata:
  labels:
    app: openshift-logforwarding-splunk
    app.kubernetes.io/component: fluentd
    app.kubernetes.io/instance: openshift-logforwarding-splunk
    app.kubernetes.io/name: openshift-logforwarding-splunk
  name: openshift-logforwarding-splunk
  namespace: openshift-logging
